name: flutter_monitoring_app
description: Aplicativo de monitoramento e alertas (skeleton)
publish_to: "none"
version: 0.1.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  sqflite_common_ffi: ^2.3.0
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.6
  flutter_local_notifications: ^13.0.0
  shared_preferences: ^2.3.0
  path_provider: ^2.1.4
  path: ^1.9.0
  web_socket_channel: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  test: ^1.21.0

flutter:
  uses-material-design: true
